project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - Schedule.qmd
    - course/index.qmd
    - 00_*
    - 01_*
website:
  google-analytics: "G-LZ35J3XE4D"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Course will start week of February 1st. Workstation setup tutorials are now available."
    type: info
    position: below-navbar 
  page-navigation: true 
  title: "Cytometry in R"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - text: "About"
        href: index.qmd
      - text: "Schedule"
        href: Schedule.qmd
      - text: "Course"
        href: course/index.qmd
    right:
    - icon: github
      href: https://github.com/UMGCCCFCSR/CytometryInR
      aria-label: GitHub
  sidebar:
    style: floating
    collapse-level: 1
    contents:
    - section: "Getting Started"
      contents:
      - text: "00 - GitHub"
        href: course/00_GitHub/index.qmd
      - text: "00 - Workstation Setup"
        href: course/00_WorkstationSetup/index.qmd
      - text: "00 - Positron"
        href: course/00_Positron/index.qmd
      - text: "00 - Git"
        href: course/00_Git/index.qmd
      - text: "00 - Quarto"
        href: course/00_Quarto/index.qmd
      - text: "00 - Getting Help"
        href: course/00_Homeworks/index.qmd
      - text: "00 - Floreada"
        href: course/00_Floreada/index.qmd
    - section: "Intro to R"
      href: Schedule.qmd
    - section: "Cytometry Core"
      href: Schedule.qmd
    - section: "Beyond the Sandbox"
      href: Schedule.qmd
    - section: "The World is your Oyster"
      href: Schedule.qmd
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: |
    ![AGPL-3.0](/images/AGPL3.png)
    ![CC-BY-SA](/images/CCBYSA.png)
format:
  html:
    css: styles.css

